# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: youshinh.md-memo
PackageVersion: 1.12.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: md-memo.exe
  PortableCommandAlias: md-memo
- RelativeFilePath: md-memo-cli.exe
  PortableCommandAlias: md-memo-cli
Commands:
- md-memo
- md-memo-cli
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/youshinh/md-memo/releases/download/v1.12.0/md-memo-windows-x64.zip
  InstallerSha256: 136137B581BC740AEAD47E7588E65664888420BA314DD00C0F2157902F2A6496
ManifestType: installer
ManifestVersion: 1.12.0
